AllCops:
  TargetRubyVersion: 2.X

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/IfUnlessModifier:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  CountRepeatedAttributes: false

Metrics/ParameterLists:
  MaxOptionalParameters: 5